(() => {
  'use strict';
  const C = window.FG_CONFIG || {};
  const qs = s => document.querySelector(s);
  const qsa = s => [...document.querySelectorAll(s)];
  const storeKey='fitglass_state_v1';
  const todayKey=()=>new Date().toISOString().slice(0,10);
  const defaultState={profile:null,meals:[],water:0,history:[],progressPhotos:[],chat:[]};
  let state={...defaultState,...load()};
  let cameraStream=null;

  function load(){try{return JSON.parse(localStorage.getItem(storeKey))||{}}catch{return {}}}
  function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
  function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function toast(msg){const t=qs('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
  function pct(a,b){return b?Math.max(0,Math.min(1,a/b)):0}
  function setRing(sel,value){const c=document.querySelector(sel);if(!c)return;const p=490*(1-value);c.style.strokeDashoffset=String(p)}
  function calc(p){
    const s=p.sex==='male'?5:-161; const bmr=Math.round(10*p.weight+6.25*p.height-5*p.age+s);
    const factors={sedentary:1.2,light:1.375,moderate:1.55,high:1.725}; const tdee=Math.round(bmr*(factors[p.activity]||1.375));
    let calories=tdee; if(p.goal==='cut') calories=Math.round(tdee*0.82); if(p.goal==='gain') calories=Math.round(tdee*1.08);
    const protein=Math.round(p.weight*(p.goal==='gain'?1.8:1.6)); const fat=Math.round(p.weight*.8); const carbs=Math.max(0,Math.round((calories-protein*4-fat*9)/4));
    const bmi=+(p.weight/((p.height/100)**2)).toFixed(1); const water=+(p.weight*.035).toFixed(1);
    const target=p.goal==='cut'?Math.max(45, +(p.weight*.9).toFixed(1)):p.goal==='gain'?+(p.weight*1.05).toFixed(1):p.weight;
    return {bmr,tdee,calories,protein,fat,carbs,bmi,water,target};
  }
  const REGIONS={
    Piura:{context:'Costa norte · clima cálido',focus:'Hidratación y control metabólico',tip:'Prioriza agua, verduras, fruta entera y preparaciones sencillas. Ajusta la hidratación a la temperatura y actividad.'},
    Cusco:{context:'Sierra sur · gran altitud',focus:'Hierro, proteína y adaptación a altitud',tip:'Combina fuentes de hierro con vitamina C. Los valores de hemoglobina deben interpretarse considerando altitud y evaluación clínica.'}
  };

  async function init(){
    try { if(window.FG_FIREBASE?.ready) await window.FG_FIREBASE.ready; } catch {}
    // Reload local state after cloud recovery has had a chance to hydrate it.
    state={...defaultState,...load()};
    registerSW();
    bindNav(); bindActions();
    if(!state.profile) showOnboarding(); else {qs('#onboarding').classList.add('hidden');renderAll();}
    const initial=state.chat.length?state.chat: [{role:'ai',text:'Hola. Soy FitGlass AI. Puedo ayudarte solo con nutrición, alimentación, hidratación, composición corporal y bienestar relacionado.'}];
    state.chat=initial; save(); renderChat();
  }
  function registerSW(){if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('sw.js').catch(()=>{})}
  function bindNav(){qsa('.nav-item').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)))}
  function showView(v){qsa('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));qsa('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v)); if(v==='coach')renderCoachProfile(); if(v==='scan')syncCameraUI()}

  function showOnboarding(){qs('#onboarding').classList.remove('hidden'); let step=0;const data={};
    const steps=[
      ()=>`<div class="eyebrow">1 / 4</div><h2>Vamos a conocerte</h2><p class="helper">Calcularemos TMB, TDEE, calorías y macros con tus datos.</p><div class="ob-grid"><div class="field"><label>Nombre</label><input id="obName" placeholder="Tu nombre"></div><div class="field"><label>Edad</label><input id="obAge" type="number" min="13" max="100" placeholder="16"></div><div class="field"><label>Sexo</label><select id="obSex"><option value="female">Mujer</option><option value="male">Hombre</option></select></div><div class="field"><label>Región</label><select id="obRegion"><option>Piura</option><option>Cusco</option></select></div></div>`,
      ()=>`<div class="eyebrow">2 / 4</div><h2>Tu cuerpo y actividad</h2><div class="ob-grid"><div class="field"><label>Peso (kg)</label><input id="obWeight" type="number" step="0.1" placeholder="70"></div><div class="field"><label>Altura (cm)</label><input id="obHeight" type="number" step="1" placeholder="170"></div><div class="field"><label>Cintura (cm)</label><input id="obWaist" type="number" step="0.1" placeholder="85"></div><div class="field"><label>Actividad</label><select id="obActivity"><option value="sedentary">Sedentaria</option><option value="light">Ligera</option><option value="moderate">Moderada</option><option value="high">Alta</option></select></div></div><div class="field full" style="margin-top:12px"><label>Objetivo</label><select id="obGoal"><option value="cut">Reducir grasa</option><option value="maintain">Mantener</option><option value="gain">Ganar masa</option></select></div>`,
      ()=>`<div class="eyebrow">3 / 4</div><h2>Tus preferencias</h2><div class="ob-grid"><div class="field full"><label>Ingredientes que te gustan</label><input id="obLikes" placeholder="pollo, pescado, avena, mango…"></div><div class="field full"><label>Alimentos que evitas</label><input id="obAvoids" placeholder="por ejemplo: lácteos, mariscos…"></div><div class="field"><label>Hemoglobina (opcional)</label><input id="obHb" type="number" step="0.1" placeholder="13.5"></div><div class="field"><label>Temperatura habitual (°C)</label><input id="obTemp" type="number" step="0.1" placeholder="30"></div></div><p class="helper">La hemoglobina solo se usa como dato orientativo. FitGlass AI no diagnostica anemia.</p>`,
      ()=>`<div class="eyebrow">4 / 4</div><h2>Tu imagen</h2><div class="profile-picker"><img id="obAvatar" src="${esc(C.APP_IMAGE_URL||'')}" alt="Foto"><div><strong>Foto de perfil</strong><p class="helper">Puedes subir una imagen ahora o pegar después una URL de Imgur.</p><input id="obPhoto" type="file" accept="image/*"></div></div><div class="glass" style="padding:14px;margin-top:14px"><strong>Antes de empezar</strong><p class="helper">Los módulos de anemia y salud son educativos. Ante síntomas o valores anormales, consulta a un profesional.</p></div>`
    ];
    function render(){qs('#stepper').innerHTML=steps.map((_,i)=>`<i class="${i<=step?'on':''}"></i>`).join('');qs('#onboardingContent').innerHTML=steps[step]();if(step===3){qs('#obPhoto')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>qs('#obAvatar').src=r.result;r.readAsDataURL(f)});}}
    function get(id){return qs(id)?.value?.trim()||''}
    function next(){
      if(step===0){data.name=get('#obName')||'Usuario';data.age=+get('#obAge')||18;data.sex=get('#obSex');data.region=get('#obRegion')||'Piura'}
      if(step===1){data.weight=+get('#obWeight');data.height=+get('#obHeight');data.waist=+get('#obWaist')||0;data.activity=get('#obActivity');data.goal=get('#obGoal');if(!(data.weight>0&&data.height>0)){toast('Completa peso y altura');return}}
      if(step===2){data.likes=get('#obLikes');data.avoids=get('#obAvoids');data.hb=+get('#obHb')||0;data.temp=+get('#obTemp')||0}
      if(step<3){step++;render()} else {const avatar=qs('#obAvatar')?.src||C.APP_IMAGE_URL;state.profile={...data,avatar};state.profile.metrics=calc(state.profile);state.history.push({date:todayKey(),weight:data.weight});save();qs('#onboarding').classList.add('hidden');renderAll();toast('Perfil creado. ¡Listo!')}
    }
    function back(){if(step>0){step--;render()} }
    qs('#onboardingContent').addEventListener('click',e=>{if(e.target.id==='obNext')next();if(e.target.id==='obBack')back()});
    const observer=new MutationObserver(()=>{const wrap=qs('#onboardingContent');if(wrap&&!wrap.querySelector('.ob-actions')){wrap.insertAdjacentHTML('beforeend',`<div class="ob-actions"><button id="obBack" class="secondary-btn" ${step===0?'disabled':''}>Atrás</button><button id="obNext" class="primary-btn">${step===3?'Entrar':'Continuar'}</button></div>`);}}); observer.observe(qs('#onboardingContent'),{childList:true}); render();
  }

  function renderAll(){const p=state.profile;if(!p)return;const m=p.metrics||calc(p);p.metrics=m;const today=state.meals.filter(x=>x.date===todayKey());const cal=today.reduce((a,x)=>a+x.calories,0),pro=today.reduce((a,x)=>a+x.protein,0);qs('#greeting').textContent=`${new Date().getHours()<12?'Buenos días':new Date().getHours()<19?'Buenas tardes':'Buenas noches'}, ${p.name}`;qs('#heroTitle').textContent='Tu progreso, de un vistazo.';qs('#heroSubtitle').textContent=`Objetivo ${labelGoal(p.goal)} · ${m.calories} kcal/día · IMC ${m.bmi}`;qs('#regionPill').textContent=p.region;qs('#goalPill').textContent=labelGoal(p.goal);qs('#profileImage').src=p.avatar||C.APP_IMAGE_URL||'';
    qs('#caloriesValue').textContent=cal;qs('#caloriesGoal').textContent=m.calories;qs('#proteinValue').textContent=`${Math.round(pro)} g`;qs('#proteinGoal').textContent=`${m.protein} g`;const waterForView=Number(state.water||0);qs('#waterValue').textContent=`${Math.round(waterForView/0.25)}`;qs('#waterGoal').textContent=`${Math.ceil(m.water/0.25)}`;qs('#weightValue').textContent=`${p.weight} kg`;qs('#targetWeightValue').textContent=`${m.target} kg`;
    const pc=pct(cal,m.calories), pp=pct(pro,m.protein), pw=pct(state.water,m.water);setRing('.ring-progress.yellow',pc);setRing('.ring-progress.green',pp);setRing('.ring-progress.blue',pw);qs('#ringCalories').textContent=Math.round(pc*100)+'%';qs('#ringProtein').textContent=Math.round(pp*100)+'%';qs('#ringWater').textContent=Math.round(pw*100)+'%';
    const r=REGIONS[p.region]||REGIONS.Piura;qs('#regionalTitle').textContent=p.region;qs('#regionBadge').textContent=p.region;qs('#regionalContext').textContent=r.context;qs('#regionalFocus').textContent=r.focus;qs('#regionalTip').textContent=r.tip;renderWeightChart();renderMacros();renderCoachProfile();
  }
  function labelGoal(g){return g==='cut'?'reducir grasa':g==='gain'?'ganar masa':'mantener'}
  function renderWeightChart(){const svg=qs('#weightChart');const data=state.history.slice(-14);if(data.length<2){svg.innerHTML=`<text x="20" y="130" fill="#758092" font-size="14">Registra al menos dos pesos para ver la tendencia.</text>`;qs('#weightDelta').textContent='—';return}const min=Math.min(...data.map(x=>x.weight))-.5,max=Math.max(...data.map(x=>x.weight))+.5;const pts=data.map((d,i)=>{const x=20+(i/(data.length-1))*660;const y=220-((d.weight-min)/(max-min))*170;return [x,y]}),poly=pts.map(p=>p.join(',')).join(' ');svg.innerHTML=`<polyline points="${poly}" fill="none" stroke="#ffd12a" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${pts.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="#fff" stroke="#ffd12a" stroke-width="3"/>`).join('')}`;const d=data[data.length-1].weight-data[0].weight;qs('#weightDelta').textContent=`${d>0?'+':''}${d.toFixed(1)} kg`}
  function renderMacros(){const p=state.profile,m=p.metrics||calc(p),today=state.meals.filter(x=>x.date===todayKey());const vals={Proteína:[today.reduce((a,x)=>a+x.protein,0),m.protein,'green'],Carbos:[today.reduce((a,x)=>a+x.carbs,0),m.carbs,'blue'],Grasas:[today.reduce((a,x)=>a+x.fat,0),m.fat,'yellow']};qs('#macroBars').innerHTML=Object.entries(vals).map(([n,[v,g,c]])=>`<div class="macro-row"><label>${n}</label><div class="bar ${c}"><i style="transform:scaleX(${pct(v,g)})"></i></div><b>${Math.round(v)}/${g}g</b></div>`).join('')}

  function bindActions(){
    qs('#profileBtn').addEventListener('click',openProfileModal);qs('#settingsBtn').addEventListener('click',openAboutModal);qs('#quickMealBtn').addEventListener('click',()=>openMealModal());
    qsa('.action-card').forEach(x=>x.addEventListener('click',()=>{const a=x.dataset.action;if(a==='water'){state.water=Math.min(state.water+0.25,9);save();renderAll();toast('Añadidos 250 ml de agua')}else if(a==='meal')openMealModal();else openProgressModal()}));
    qs('#enableCameraBtn').addEventListener('click',startCamera);qs('#captureBtn').addEventListener('click',capturePhoto);qs('#stopCameraBtn').addEventListener('click',stopCamera);qs('#uploadPhotoBtn').addEventListener('click',()=>qs('#photoInput').click());qs('#photoInput').addEventListener('change',e=>{const f=e.target.files?.[0];if(f)analyzeImageFile(f)});
    qs('#sendChatBtn').addEventListener('click',sendChat);qs('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChat()}});
  }
  function openModal(html){qs('#modalHost').innerHTML=`<div class="modal" id="activeModal"><div class="glass modal-card">${html}</div></div>`;qs('#activeModal').addEventListener('click',e=>{if(e.target.id==='activeModal')closeModal()})}
  function closeModal(){qs('#modalHost').innerHTML=''}
  function openProfileModal(){const p=state.profile;if(!p)return;openModal(`<div class="modal-head"><h2>Perfil</h2><button class="icon-btn" onclick="window.FGClose()"><span class="svg-icon close"></span></button></div><div class="form-stack"><div class="profile-picker"><img src="${esc(p.avatar||C.APP_IMAGE_URL||'')}" alt="Foto"><div><strong>${esc(p.name)}</strong><div class="helper">${p.region} · ${p.age} años</div></div></div><div class="coach-profile-grid"><div class="cp"><small>TMB</small><strong>${p.metrics.bmr} kcal</strong></div><div class="cp"><small>TDEE</small><strong>${p.metrics.tdee} kcal</strong></div><div class="cp"><small>IMC</small><strong>${p.metrics.bmi}</strong></div><div class="cp"><small>Meta</small><strong>${p.metrics.target} kg</strong></div></div><button class="secondary-btn" id="editProfileBtn">Editar perfil</button></div>`);qs('#editProfileBtn').addEventListener('click',()=>{closeModal();showOnboarding();})}
  function openAboutModal(){openModal(`<div class="modal-head"><h2>Sobre FitGlass AI</h2><button class="icon-btn" onclick="window.FGClose()"><span class="svg-icon close"></span></button></div><div class="form-stack"><div class="glass" style="padding:15px"><strong>Diseñada por Andre y Sebastian</strong><p class="helper">Proyecto desarrollado por estudiantes del IEP El Triunfo Castilla, aula Mateo García Pumacahua, 4.º de secundaria.</p><button class="secondary-btn" id="moreBtn">¿Quieres saber más de ellos?</button><p id="moreText" class="helper hidden">Los desarrolladores son Andre y Sebastian.</p></div><div class="glass" style="padding:15px"><strong>Modo de IA</strong><p class="helper">Coach restringido a nutrición, alimentación y bienestar relacionado. Las funciones de salud son educativas y no sustituyen evaluación profesional.</p></div><button class="primary-btn" id="resetBtn">Restablecer datos locales</button></div>`);qs('#moreBtn').addEventListener('click',()=>qs('#moreText').classList.toggle('hidden'));qs('#resetBtn').addEventListener('click',()=>{if(confirm('¿Borrar el perfil y registros locales?')){localStorage.removeItem(storeKey);location.reload()}})}
  window.FGClose=closeModal;

  function openMealModal(){openModal(`<div class="modal-head"><h2>Registrar comida</h2><button class="icon-btn" onclick="window.FGClose()"><span class="svg-icon close"></span></button></div><div class="form-stack"><div class="field"><label>Nombre del plato</label><input id="mealName" placeholder="Arroz con pollo"></div><div class="ob-grid"><div class="field"><label>Calorías</label><input id="mealCal" type="number" placeholder="550"></div><div class="field"><label>Proteína (g)</label><input id="mealPro" type="number" placeholder="35"></div><div class="field"><label>Carbohidratos (g)</label><input id="mealCarb" type="number" placeholder="60"></div><div class="field"><label>Grasas (g)</label><input id="mealFat" type="number" placeholder="18"></div></div><button class="primary-btn" id="saveMealBtn">Guardar comida</button></div>`);qs('#saveMealBtn').addEventListener('click',()=>{const x={id:crypto.randomUUID?.()||String(Date.now()),date:todayKey(),name:qs('#mealName').value||'Comida',calories:+qs('#mealCal').value||0,protein:+qs('#mealPro').value||0,carbs:+qs('#mealCarb').value||0,fat:+qs('#mealFat').value||0};state.meals.push(x);save();closeModal();renderAll();toast('Comida guardada')})}
  function openProgressModal(){const p=state.profile;openModal(`<div class="modal-head"><h2>Actualizar peso</h2><button class="icon-btn" onclick="window.FGClose()"><span class="svg-icon close"></span></button></div><div class="form-stack"><div class="field"><label>Peso actual (kg)</label><input id="newWeight" type="number" step="0.1" value="${p.weight}"></div><button class="primary-btn" id="saveWeightBtn">Guardar progreso</button></div>`);qs('#saveWeightBtn').addEventListener('click',()=>{const w=+qs('#newWeight').value;if(!(w>0))return;state.profile.weight=w;state.profile.metrics=calc(state.profile);state.history.push({date:todayKey(),weight:w});save();closeModal();renderAll();toast('Progreso actualizado')})}

  async function startCamera(){if(!navigator.mediaDevices?.getUserMedia){toast('Tu navegador no permite acceso a cámara');return}try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});qs('#cameraPreview').srcObject=cameraStream;qs('#cameraPlaceholder').classList.add('hidden');qs('#cameraStatus').textContent='Cámara activa';toast('Permiso de cámara concedido')}catch(err){toast('Permiso de cámara rechazado o no disponible')}}
  function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}qs('#cameraPreview').srcObject=null;qs('#cameraPlaceholder').classList.remove('hidden');qs('#cameraStatus').textContent='Cámara lista'}
  function syncCameraUI(){}
  function capturePhoto(){if(!cameraStream){toast('Activa la cámara primero');return}const v=qs('#cameraPreview'),c=document.createElement('canvas');c.width=v.videoWidth||1280;c.height=v.videoHeight||720;c.getContext('2d').drawImage(v,0,0,c.width,c.height);c.toBlob(blob=>analyzeImageFile(new File([blob],'captura.jpg',{type:'image/jpeg'})),'image/jpeg',.9)}
  async function analyzeImageFile(file){const reader=new FileReader();reader.onload=()=>{qs('#analysisResult').innerHTML=`<div class="analysis-result"><div class="panel-head"><div><h3 style="margin:0">Imagen recibida</h3><small style="color:var(--muted)">Analizando…</small></div></div><div class="glass" style="padding:12px"><img src="${reader.result}" alt="Comida" style="width:100%;max-height:260px;object-fit:cover;border-radius:15px"></div><div class="analysis-total"><strong id="analysisStatus">IA en proceso</strong><p class="helper">Se intentará usar la API de visión configurada. Sin clave, se activa el modo demostración.</p></div></div>`;};reader.readAsDataURL(file);
    if((C.GROQ_PROXY_URL||C.GROQ_API_KEY) && C.ENABLE_API){try{const b64=await fileToData(file);const result=await groqVision(b64);renderAnalysis(result)}catch(e){renderAnalysis(demoVision())}} else renderAnalysis(demoVision());
  }
  async function fileToData(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
  function demoVision(){return {summary:'Modo demostración: plato equilibrado detectado.',foods:[['Proteína principal',140,240],['Arroz / cereal',180,235],['Verduras',90,35],['Aceite / salsa',8,72]],calories:582,protein:36,carbs:61,fat:20}}
  async function groqVision(b64){const prompt=`Analiza esta foto de comida. Responde SOLO JSON válido con: summary, foods (array de {name,grams,calories}), calories, protein, carbs, fat. No diagnostiques salud.`;const r=await fetch(C.GROQ_PROXY_URL||'https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{...(C.GROQ_PROXY_URL?{}:{'Authorization':'Bearer '+C.GROQ_API_KEY}),'Content-Type':'application/json'},body:JSON.stringify({model:C.GROQ_VISION_MODEL||'qwen/qwen3.6-27b',temperature:.1,max_tokens:1200,messages:[{role:'system',content:'Eres un analizador nutricional. Devuelve solo JSON.'},{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:'data:image/jpeg;base64,'+b64}}]}]})});if(!r.ok)throw new Error('Groq error');const j=await r.json();const text=j.choices?.[0]?.message?.content||'';const clean=text.replace(/```json|```/g,'').trim();return JSON.parse(clean)}
  function renderAnalysis(x){const foods=(x.foods||[]).map(f=>Array.isArray(f)?f:[f.name,f.grams,f.calories]);qs('#analysisResult').innerHTML=`<div class="analysis-result"><div class="panel-head"><div><h3 style="margin:0">${esc(x.summary||'Análisis completado')}</h3><small style="color:var(--muted)">${C.GROQ_API_KEY?'Vision IA':'Modo demostración'}</small></div><span class="ai-badge">OK</span></div>${foods.map(f=>`<div class="food-line"><div><strong>${esc(f[0])}</strong><small>${esc(f[1])} g aprox.</small></div><strong>${Math.round(+f[2]||0)} kcal</strong></div>`).join('')}<div class="analysis-total"><small>Total estimado</small><div style="margin-top:4px"><strong>${Math.round(x.calories||0)} kcal</strong></div><p class="helper">Proteína ${Math.round(x.protein||0)} g · Carbos ${Math.round(x.carbs||0)} g · Grasas ${Math.round(x.fat||0)} g</p></div><button class="primary-btn" id="saveAnalysisBtn">Guardar como comida</button></div>`;qs('#saveAnalysisBtn').addEventListener('click',()=>{state.meals.push({id:crypto.randomUUID?.()||String(Date.now()),date:todayKey(),name:'Foto IA',calories:+x.calories||0,protein:+x.protein||0,carbs:+x.carbs||0,fat:+x.fat||0});save();renderAll();toast('Análisis guardado')})}

  function renderChat(){const box=qs('#chatMessages');box.innerHTML=state.chat.map(m=>`<div class="bubble ${m.role==='user'?'user':'ai'}">${esc(m.text).replace(/\n/g,'<br>')}</div>`).join('');box.scrollTop=box.scrollHeight}
  function renderCoachProfile(){const p=state.profile;if(!p)return;qs('#coachProfile').innerHTML=`<div class="coach-profile-grid"><div class="cp"><small>Región</small><strong>${esc(p.region)}</strong></div><div class="cp"><small>Objetivo</small><strong>${esc(labelGoal(p.goal))}</strong></div><div class="cp"><small>Calorías</small><strong>${p.metrics.calories} kcal</strong></div><div class="cp"><small>Proteína</small><strong>${p.metrics.protein} g</strong></div></div>`}
  async function sendChat(){const input=qs('#chatInput');const text=input.value.trim();if(!text)return;state.chat.push({role:'user',text});input.value='';renderChat();const allowed=/(nutri|calor|prote|carbo|grasa|agua|hidrat|anemia|hemoglob|hierro|vitamin|comer|alimento|receta|peso|imc|ejercicio|masa|obes|dieta|salud)/i.test(text);if(!allowed){const msg='Soy FitGlass AI. Solo puedo responder preguntas relacionadas con nutrición, alimentación, hidratación y bienestar relacionado.';state.chat.push({role:'ai',text:msg});save();renderChat();return}
    let answer=''; if(C.ENABLE_API&&(C.GROQ_PROXY_URL||C.GROQ_API_KEY)){try{answer=await groqCoach(text)}catch{answer=localCoach(text)}}else answer=localCoach(text);state.chat.push({role:'ai',text:answer});save();renderChat()}
  function localCoach(t){const p=state.profile,m=p.metrics;if(/calor/i.test(t))return `Tu referencia actual es de ${m.calories} kcal/día, calculada desde tu metabolismo y actividad. Hoy llevas ${Math.round(state.meals.filter(x=>x.date===todayKey()).reduce((a,x)=>a+x.calories,0))} kcal.`;if(/anemia|hemoglob/i.test(t))return p.hb?`Registraste ${p.hb} g/dL de hemoglobina. Ese dato debe interpretarse según edad, sexo, altitud y contexto clínico; FitGlass AI no puede diagnosticar anemia.`:'No has registrado hemoglobina. Puedes añadirla en tu perfil y usar el módulo como orientación educativa, no como diagnóstico.';if(/agua|hidrat/i.test(t))return `Tu meta estimada es ${m.water} L/día. En ${p.region}, adapta la cantidad a temperatura, sudoración y ejercicio.`;if(/prote/i.test(t))return `Tu meta calculada es ${m.protein} g de proteína al día, distribuida entre tus comidas.`;return `Según tu perfil de ${p.region}, enfócate en alimentos mínimamente procesados, una buena fuente de proteína, vegetales, fruta entera, agua y porciones acordes con tu objetivo.`}
  async function groqCoach(text){const p=state.profile,m=p.metrics;const system=`Eres FitGlass AI, un asistente de nutrición. RESTRICCIÓN ABSOLUTA: responde SOLO sobre nutrición, alimentación, hidratación, composición corporal y bienestar relacionado. Rechaza con una frase breve cualquier tema ajeno. No diagnostiques anemia ni otras enfermedades; ante síntomas o valores preocupantes recomienda evaluación profesional. Usa el perfil del usuario como contexto. Región: ${p.region}. Edad: ${p.age}. Sexo: ${p.sex}. Peso: ${p.weight} kg. Altura: ${p.height} cm. Objetivo: ${labelGoal(p.goal)}. Calorías objetivo: ${m.calories}. Proteína objetivo: ${m.protein} g. Preferencias: ${p.likes||'ninguna'}. Evita: ${p.avoids||'ninguno'}.`;const r=await fetch(C.GROQ_PROXY_URL||'https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{...(C.GROQ_PROXY_URL?{}:{'Authorization':'Bearer '+C.GROQ_API_KEY}),'Content-Type':'application/json'},body:JSON.stringify({model:C.GROQ_MODEL||'openai/gpt-oss-120b',temperature:.2,max_tokens:800,messages:[{role:'system',content:system},{role:'user',content:text}]})});if(!r.ok)throw new Error('groq');const j=await r.json();return j.choices?.[0]?.message?.content||localCoach(text)}

  init();
})();
