/* FitGlass AI — food catalog. Names only; nutrient facts should be resolved through USDA/OFF. */
(function(){
  "use strict";
  const foods=[];
  const CAT_PROTEÍNA=[];
  CAT_PROTEÍNA.push({id:'food-0001',name:"pollo a la plancha",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0002',name:"pollo al horno",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0003',name:"pollo sancochado",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0004',name:"pechuga de pollo",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0005',name:"pavo",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0006',name:"carne de res magra",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0007',name:"carne molida",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0008',name:"lomo de res",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0009',name:"hígado de res",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0010',name:"pescado blanco",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0011',name:"bonito",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0012',name:"caballa",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0013',name:"jurel",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0014',name:"atún",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0015',name:"sardina",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0016',name:"trucha",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0017',name:"salmón",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0018',name:"merluza",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0019',name:"anchoveta",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0020',name:"huevo",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0021',name:"clara de huevo",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0022',name:"yogur natural",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0023',name:"yogur griego",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0024',name:"queso fresco",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0025',name:"queso ricota",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0026',name:"leche descremada",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0027',name:"leche evaporada",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0028',name:"lenteja",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0029',name:"frejol",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0030',name:"garbanzo",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0031',name:"haba",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0032',name:"tarwi",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0033',name:"soya",category:"proteína"});
  CAT_PROTEÍNA.push({id:'food-0034',name:"tofu",category:"proteína"});
  const CAT_CARBOHIDRATO=[];
  CAT_CARBOHIDRATO.push({id:'food-0035',name:"arroz blanco",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0036',name:"arroz integral",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0037',name:"avena",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0038',name:"quinua",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0039',name:"kiwicha",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0040',name:"trigo",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0041',name:"cebada",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0042',name:"maíz",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0043',name:"choclo",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0044',name:"cancha",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0045',name:"pan integral",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0046',name:"pan francés",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0047',name:"camote",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0048',name:"papa blanca",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0049',name:"papa amarilla",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0050',name:"papa nativa",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0051',name:"yuca",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0052',name:"oca",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0053',name:"olluco",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0054',name:"mashua",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0055',name:"plátano bellaco",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0056',name:"plátano de seda",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0057',name:"fideos",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0058',name:"pasta integral",category:"carbohidrato"});
  CAT_CARBOHIDRATO.push({id:'food-0059',name:"cuscús",category:"carbohidrato"});
  const CAT_FRUTA=[];
  CAT_FRUTA.push({id:'food-0060',name:"mango",category:"fruta"});
  CAT_FRUTA.push({id:'food-0061',name:"plátano",category:"fruta"});
  CAT_FRUTA.push({id:'food-0062',name:"papaya",category:"fruta"});
  CAT_FRUTA.push({id:'food-0063',name:"naranja",category:"fruta"});
  CAT_FRUTA.push({id:'food-0064',name:"mandarina",category:"fruta"});
  CAT_FRUTA.push({id:'food-0065',name:"limón",category:"fruta"});
  CAT_FRUTA.push({id:'food-0066',name:"lima",category:"fruta"});
  CAT_FRUTA.push({id:'food-0067',name:"maracuyá",category:"fruta"});
  CAT_FRUTA.push({id:'food-0068',name:"granadilla",category:"fruta"});
  CAT_FRUTA.push({id:'food-0069',name:"piña",category:"fruta"});
  CAT_FRUTA.push({id:'food-0070',name:"sandía",category:"fruta"});
  CAT_FRUTA.push({id:'food-0071',name:"melón",category:"fruta"});
  CAT_FRUTA.push({id:'food-0072',name:"fresa",category:"fruta"});
  CAT_FRUTA.push({id:'food-0073',name:"arándano",category:"fruta"});
  CAT_FRUTA.push({id:'food-0074',name:"uva",category:"fruta"});
  CAT_FRUTA.push({id:'food-0075',name:"manzana",category:"fruta"});
  CAT_FRUTA.push({id:'food-0076',name:"pera",category:"fruta"});
  CAT_FRUTA.push({id:'food-0077',name:"durazno",category:"fruta"});
  CAT_FRUTA.push({id:'food-0078',name:"ciruela",category:"fruta"});
  CAT_FRUTA.push({id:'food-0079',name:"guayaba",category:"fruta"});
  CAT_FRUTA.push({id:'food-0080',name:"granada",category:"fruta"});
  CAT_FRUTA.push({id:'food-0081',name:"kiwi",category:"fruta"});
  CAT_FRUTA.push({id:'food-0082',name:"palta",category:"fruta"});
  CAT_FRUTA.push({id:'food-0083',name:"coco",category:"fruta"});
  const CAT_VERDURA=[];
  CAT_VERDURA.push({id:'food-0084',name:"tomate",category:"verdura"});
  CAT_VERDURA.push({id:'food-0085',name:"zanahoria",category:"verdura"});
  CAT_VERDURA.push({id:'food-0086',name:"espinaca",category:"verdura"});
  CAT_VERDURA.push({id:'food-0087',name:"acelga",category:"verdura"});
  CAT_VERDURA.push({id:'food-0088',name:"brócoli",category:"verdura"});
  CAT_VERDURA.push({id:'food-0089',name:"coliflor",category:"verdura"});
  CAT_VERDURA.push({id:'food-0090',name:"lechuga",category:"verdura"});
  CAT_VERDURA.push({id:'food-0091',name:"pepino",category:"verdura"});
  CAT_VERDURA.push({id:'food-0092',name:"pimiento",category:"verdura"});
  CAT_VERDURA.push({id:'food-0093',name:"cebolla",category:"verdura"});
  CAT_VERDURA.push({id:'food-0094',name:"ajo",category:"verdura"});
  CAT_VERDURA.push({id:'food-0095',name:"vainita",category:"verdura"});
  CAT_VERDURA.push({id:'food-0096',name:"zapallito italiano",category:"verdura"});
  CAT_VERDURA.push({id:'food-0097',name:"zapallo",category:"verdura"});
  CAT_VERDURA.push({id:'food-0098',name:"berenjena",category:"verdura"});
  CAT_VERDURA.push({id:'food-0099',name:"betarraga",category:"verdura"});
  CAT_VERDURA.push({id:'food-0100',name:"rabanito",category:"verdura"});
  CAT_VERDURA.push({id:'food-0101',name:"repollo",category:"verdura"});
  CAT_VERDURA.push({id:'food-0102',name:"apio",category:"verdura"});
  CAT_VERDURA.push({id:'food-0103',name:"culantro",category:"verdura"});
  CAT_VERDURA.push({id:'food-0104',name:"perejil",category:"verdura"});
  CAT_VERDURA.push({id:'food-0105',name:"choclo tierno",category:"verdura"});
  CAT_VERDURA.push({id:'food-0106',name:"arveja",category:"verdura"});
  CAT_VERDURA.push({id:'food-0107',name:"alcachofa",category:"verdura"});
  const CAT_GRASA=[];
  CAT_GRASA.push({id:'food-0108',name:"palta",category:"grasa"});
  CAT_GRASA.push({id:'food-0109',name:"aceite de oliva",category:"grasa"});
  CAT_GRASA.push({id:'food-0110',name:"aceite vegetal",category:"grasa"});
  CAT_GRASA.push({id:'food-0111',name:"maní",category:"grasa"});
  CAT_GRASA.push({id:'food-0112',name:"nuez",category:"grasa"});
  CAT_GRASA.push({id:'food-0113',name:"almendra",category:"grasa"});
  CAT_GRASA.push({id:'food-0114',name:"castaña",category:"grasa"});
  CAT_GRASA.push({id:'food-0115',name:"semilla de chía",category:"grasa"});
  CAT_GRASA.push({id:'food-0116',name:"semilla de linaza",category:"grasa"});
  CAT_GRASA.push({id:'food-0117',name:"semilla de girasol",category:"grasa"});
  CAT_GRASA.push({id:'food-0118',name:"semilla de zapallo",category:"grasa"});
  CAT_GRASA.push({id:'food-0119',name:"aceituna",category:"grasa"});
  CAT_GRASA.push({id:'food-0120',name:"mantequilla de maní",category:"grasa"});
  const CAT_BEBIDA=[];
  CAT_BEBIDA.push({id:'food-0121',name:"agua",category:"bebida"});
  CAT_BEBIDA.push({id:'food-0122',name:"agua con limón",category:"bebida"});
  CAT_BEBIDA.push({id:'food-0123',name:"infusión sin azúcar",category:"bebida"});
  CAT_BEBIDA.push({id:'food-0124',name:"té verde",category:"bebida"});
  CAT_BEBIDA.push({id:'food-0125',name:"café sin azúcar",category:"bebida"});
  CAT_BEBIDA.push({id:'food-0126',name:"leche descremada",category:"bebida"});
  CAT_BEBIDA.push({id:'food-0127',name:"emoliente sin azúcar",category:"bebida"});
  const groups={protein:CAT_PROTEINA,carbohydrate:CAT_CARBOHIDRATO,fruit:CAT_FRUTA,vegetable:CAT_VERDURA,fat:CAT_GRASA,drink:CAT_BEBIDA};
  groups.all=Object.values(groups).filter(Array.isArray).flat();
  function search(term){const q=String(term||"").toLowerCase().trim();if(!q)return groups.all.slice(0,30);return groups.all.filter(x=>x.name.toLowerCase().includes(q)).slice(0,30);}
  function byCategory(category){return (groups[category]||[]).slice();}
  function categories(){return Object.keys(groups).filter(k=>k!=="all");}
  function randomSuggestions(category,count=6){const a=byCategory(category);const out=[];for(let i=0;i<Math.min(count,a.length);i++){out.push(a[(i*7+3)%a.length]);}return out;}
  window.FG_FOOD_CATALOG={foods:groups.all,groups,search,byCategory,categories,randomSuggestions};
})();
